### ISSUE TITLE
Store SpriteSettings Feature

### ISSUE THREAD

**Issue by edwardrowe** [bogdanrybak/sprite-settings-utility#2]
Here are my thoughts on how storing and apply saved SpriteSettings would work. I have some additional ideas, but this provides a good framework for future enhancements. Let me know if this is along the lines of what you were thinking.
**The Quick Sprite Settings Window**
![quick sprite settings mockup simplified](https://cloud.githubusercontent.com/assets/398377/10865808/f83ae384-7fee-11e5-876b-13d17804087b.jpg)

**Settings Config** (For now this would be the scriptable object, but I'd like to consider making it accessible through a menu item and possibly hidden in inspector. I'll have to read up on some Editor Settings tutorials, but I've seen some good examples on other assets.
![quick sprite setting - settingsconfig](https://cloud.githubusercontent.com/assets/398377/10865779/cc043000-7fed-11e5-9bbb-6238be30c283.jpg)

**Comment by bogdanrybak** [comment]
I think keeping all the different settings in a scriptable object makes sense for collaboration purposes. It can be stored in the project and used by everyone. Most frequently used options that are not directly part of a "Sprite Settings" entry can go into EditorPrefs - pivot override, packing tag override, last selected setting. The problem right now is the above fields that frequently change are clumped together with the settings thus constantly affecting the scriptable object while using the tool.

I like the new structure, great work!

**Comment by edwardrowe** [comment]
Yeah that makes sense on storing last used setting and other local data in the EditorPrefs. Cool thanks, I'll give this a shot and submit a PR later this week.
